### ISSUE TITLE
Question: EmitAsync Stacking (blocking?)

### ISSUE THREAD

**Issue by mbrehme** [doghappy/socket.io-client-csharp#129]
Hey,

first of all thanks for providing such a sophisticated SocketIOClient implementation!

I just ran into an problem where I need your help:

- We plan to send a lot of messages through the client ( 20 msg/sec )
- The RTT we measured with a reference implementation (node js) in the same situation is like 40ms 
- If I send more than 5 message/second with the c# client it seems that the message are kind of keep stacking itself and the duration of EmitAsync increases steady.

I saw that there is a semaphore in your code which blocks later send until the previous are completely handled could this be a correlate?

@doghappy Do you have an idea regarding this kind of bottleneck? Is the library designed this way. Should I open more connection or look for other implementations?

Thanks, again

**Comment by doghappy** [comment]
## Short answer

> Do you have an idea regarding this kind of bottleneck?

no yet

> Should I open more connection or look for other implementations?

If you want to build a high-performance application, you should look for a better implementation. (There is no official client implementation for .NET) 

## Tests

server:

```js
io.on("connection", socket => {
    socket.on("rtt", data => socket.emit("rtt", data));
});
```

nodejs client:

```js
var dic = [];
var send = -1;
var result = [];

socket.on("connect", () => {
    for (var i = 0; i < 1000; i++) {
        send++;
        dic.push({
            key: send,
            val: new Date()
        });
        socket.emit("rtt", send);
    }
});

socket.on("rtt", no => {
    var item = dic.find(i => i.key === no);
    var ms = Math.abs(new Date() - item.val);
    result.push(ms);

    if (no >= 999) {
        var sum = result.reduce((a, b) => a + b, 0);
        var avg = (sum / result.length) || 0;
        console.log(avg);
        process.exit();
    }
});
```

SocketIOClient

```cs
var dic = new Dictionary<int, DateTime>();
var result = new double[1000];
client.On("rtt", response =>
{
    var no = response.GetValue<int>();
    result[no] = (DateTime.Now - dic[no]).TotalMilliseconds;
    if (no >= 999)
    {
        Console.WriteLine(result.Average());
        Environment.Exit(0);
    }
});


client.OnConnected += async (sender, e) =>
{
    DateTime now = DateTime.Now;
    for (int i = 0; i < 1000; i++)
    {
        send++;
        dic.Add(send, DateTime.Now);
        await client.EmitAsync("rtt", send);
    }
};
await client.ConnectAsync();
Console.ReadLine();
```

### Unstable network

I deployed the server to a remote server (**Unstable network**), test results:

| nodejs client | SocketIOClient with `SemaphoreSlim` lock | SocketIOClient **without** `SemaphoreSlim` lock |
| :- | :- | :- |
| 1257.359 | 752.5036898 | 875.8924 |
| 1680.06 | 1563.25098 | 827.6339922 |
| 8779.675 | 1523.898286 | 1342.882568 |
| 565.99 | 6128.975464 | 955.0949267 |
| 1759.634 | 1581.777189 | 1012.778691 |
| 1570.435 | 792.3239924 | 10930.19723 |
| 1870.808 | 998.0244449 | 1602.562642 |
| 1033.061 | 2262.0548 | 1219.132525 |
| 985.205 | 2397.879999 | 1770.336658 |
| 909.302 | 1088.69652 | 1742.949496 |

avg(nodejs client): 2041.1529  
avg(SocketIOClient with `SemaphoreSlim` lock): 1908.938537  
avg(SocketIOClient **without** `SemaphoreSlim` lock): 2227.946113

Due to the unstable network, the test results cannot explain the problem.

### Localhost network

| nodejs client | SocketIOClient with `SemaphoreSlim` lock | SocketIOClient **without** `SemaphoreSlim` lock |
| :- | :- | :- |
| 52.222 | 21.2546707 | 21.90660 |
| 52.59 | 21.66709919 | 21.48461 |
| 52.75 | 20.9969031 | 21.2132584 |
| 52.768 | 22.05542 | 21.186576 |
| 52.138 | 21.44150 | 21.58489809 |
| 55.436 | 21.45624 | 21.78578 |
| 53.33 | 21.71954 | 21.7320 |
| 52.56 | 21.060892 | 21.00908 |
| 51.885 | 21.656514 | 21.657258 |
| 54.604 | 21.088 | 21.69231 |

Due to the low payload on the client, there is little difference between locked and unlocked

**Comment by mbrehme** [comment]
@doghappy thanks for digging into the problem!

Thanks to your clarifications I was able to kind of workaround my issue by moving from an on demand send to an interval:

- push messages in an queue
- bulk sending the messages on timer interval in the other thread (`System.Threading.Timer`)

Thanks again for your very quick help!
