### ISSUE TITLE
Problem .net standard 2

### ISSUE THREAD

**Issue by mehdi-nejati** [doghappy/socket.io-client-csharp#35]
Hi, thanks a lot.
I had a project on .net framework 4.5 and I have to use socket.io for connecting to server . I know .net standard 2 on .net framework 4.7 . Is there any way that I can use this package?

**Comment by doghappy** [comment]
This library depends on the [WebSocket.Client](https://github.com/Marfusios/websocket-client), and its target framework is .net standard 2. Maybe you can fork/clone these two repositories, change the target framework, and reference your changed project instead of NuGet

https://docs.microsoft.com/zh-cn/dotnet/standard/net-standard#net-implementation-support
