### ISSUE TITLE
Emit with callback

### ISSUE THREAD

**Issue by fob71** [doghappy/socket.io-client-csharp#6]
Right now "EmitAsync" accepts two parameters: "event" and "object".

Native implementation of method emit in socket.io is:
```
emit(event: string, payload?: any, callback?: Function): void
```
Is there any workaround to achieve the callback. Doing nothing, error: "TypeError: callback is not a function" is thrown in server.

Would it be possible to implement callback in EmitAsync ?

Thanks in advance

**Comment by doghappy** [comment]
Thanks for your feedback, I will implement it.

**Comment by doghappy** [comment]
**Temporarily blocked**. The reason is: When I added a callback function to the server, I use SocketIOClient to Emit the event, the callback obtained by the server is undefined, but it's worked when I use the [tool](https://amritb.github.io/socketio-client-tool). what seems to be missing? checking...

may be this [answer](https://stackoverflow.com/a/13550139/7771913) is helpfull to you

**Comment by doghappy** [comment]
Need to construct a packet, send buffer to server🤔

**Comment by doghappy** [comment]
Find the problem, I'll implement it.

**Comment by doghappy** [comment]
I've found a solution and an update will be released in 2 days.

**Comment by doghappy** [comment]
@fob71 Hi, I'm pushed code to master, and if it works, I'll publish it to NuGet.

An overload was added:

```cs
Task EmitAsync(string eventName, object obj, EventHandler callback);
```

usage

```cs
await client.EmitAsync("callback", guid, res =>
{
    text = res.Text;
});
```

**Comment by fob71** [comment]
Works fine... great job. 

Publish it to Nuget when you can.

**Comment by doghappy** [comment]
1.0.2 is available, please update the NuGet package
