### ISSUE TITLE
The WebSocket protocol is not supported on this platform

### ISSUE THREAD

**Issue by martingercke** [doghappy/socket.io-client-csharp#69]
Hi @doghappy,
we use version 2.0.1 and still get the error on Windows 7 as described in closed issue #50.
I guess that issue should be reopened.
We cannot verify that it worked in a previous version (<2.0) and stopped working with the major rework in 2.0.0 or if it never worked, even with versions <2.0
Can you maybe explain the internals how socket.io-client-csharp is built up to get around the websockets requirement which is not included in Windows 7?
From the description from Microsoft I get that only abstract classes have been implemented for WebSockets in Windows 7:
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket?view=netcore-3.1
Can you explain how your library or System.Net.WebSockets.Client.Managed and System.Net.WebSockets.Client solve this issue?
Thank you very much in advance!

**Comment by doghappy** [comment]
I created a new project for Windows 7, and you can pull the code. Add an existing project in VS and reference it.

https://github.com/doghappy/socket.io-client-csharp/tree/windows7/src/SocketIOClient.Windows7

project name: SocketIOClient.Windows7

This is only a temporary plan, I will post to NuGet in the future

**Comment by doghappy** [comment]
If your TargetFramework is `.NET Framework` and it runs on `Windows7/Windows Server 2008 R2`, please install [![NuGet](https://img.shields.io/badge/NuGet-SocketIOClient.NetFx-%23004880)](https://www.nuget.org/packages/SocketIOClient.NetFx)

Otherwise, we recommend you to install [![NuGet](https://img.shields.io/badge/NuGet-SocketIOClient-%23004880)](https://www.nuget.org/packages/SocketIOClient)
